package handler

import "strings"

// allowedEmailDomains is the set of permitted email provider domains.
// Any email whose domain is not in this set will be rejected at OTP request time.
var allowedEmailDomains = map[string]struct{}{
	"gmail.com":       {},
	"outlook.com":     {},
	"hotmail.com":     {},
	"yahoo.com":       {},
	"icloud.com":      {},
	"me.com":          {},
	"msn.com":         {},
	"aol.com":         {},
	"proton.me":       {},
	"zoho.com":        {},
	"ymail.com":       {},
	"rocketmail.com":  {},
	"protonmail.com":  {},
	"mail.ru":         {},
	"yandex.com":      {},
	"yandex.ru":       {},
	"list.ru":         {},
	"bk.ru":           {},
	"inbox.ru":        {},
	"gmx.com":         {},
	"gmx.net":         {},
	"web.de":          {},
	"freenet.de":      {},
	"t-online.de":     {},
	"orange.fr":       {},
	"wanadoo.fr":      {},
	"free.fr":         {},
	"sfr.fr":          {},
	"laposte.net":     {},
	"libero.it":       {},
	"virgilio.it":     {},
	"tiscali.it":      {},
	"alice.it":        {},
	"uol.com.br":      {},
	"bol.com.br":      {},
	"terra.com.br":    {},
	"ig.com.br":       {},
	"globo.com":       {},
	"rediffmail.com":  {},
	"indiatimes.com":  {},
	"qq.com":          {},
	"163.com":         {},
	"126.com":         {},
	"sina.com":        {},
	"sohu.com":        {},
	"naver.com":       {},
	"daum.net":        {},
	"hanmail.net":     {},
	"comcast.net":     {},
	"verizon.net":     {},
	"att.net":         {},
	"sbcglobal.net":   {},
	"bellsouth.net":   {},
	"charter.net":     {},
	"cox.net":         {},
	"earthlink.net":   {},
	"optonline.net":   {},
	"shaw.ca":         {},
	"rogers.com":      {},
	"bell.net":        {},
	"sympatico.ca":    {},
	"sky.com":         {},
	"virginmedia.com": {},
	"telstra.com":     {},
	"bigpond.com":     {},
	"tuta.io":         {},
	"tuta.com":        {},
	"mailfence.com":   {},
	"hushmail.com":    {},
	"runbox.com":      {},
	"yahoo.co.uk":     {},
	"outlook.sa":      {},
	"outlook.fr":      {},
	"hotmail.co.uk":   {},
	"yahoo.ca":        {},
	"live.com":        {},
	"live.co.uk":      {},
	"live.fr":         {},
	"outlook.de":      {},
	"outlook.com.br":  {},
	"yahoo.de":        {},
	"yahoo.in":        {},
	"yahoo.com.br":    {},
	"yahoo.com.ar":    {},
	"pm.me":           {},
}

// isEmailDomainAllowed returns true if the email's domain is in the allowlist.
func isEmailDomainAllowed(email string) bool {
	at := strings.LastIndex(email, "@")
	if at < 0 {
		return false
	}
	domain := strings.ToLower(email[at+1:])
	_, ok := allowedEmailDomains[domain]
	return ok
}
